# Generated by Django 5.0.3 on 2024-03-25 04:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 24, 22, 56, 54, 811360)),
        ),
        migrations.AddField(
            model_name='room',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 24, 22, 56, 54, 811360)),
        ),
    ]
